repos:
  -   repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
      - id: black
        language_version: python3
        exclude: versioneer.py
        args:
          - --target-version=py38
  -   repo: https://gitlab.com/pycqa/flake8
      rev: 3.9.2
      hooks:
      - id: flake8
        language_version: python3
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        # Override default --ignore-missing-imports
        # Use setup.cfg if possible instead of adding command line parameters here
        args: [--warn-unused-configs]
        # additional_dependencies:
        #   # Type stubs
        #   - types-setuptools
        #   # Typed libraries
        #   - numpy
